src/Entity/Computer.php
<?php

namespace App\Entity;

use App\Repository\ComputerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ComputerRepository::class)]
class Computer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $model = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?int $release_year = null;

    #[ORM\Column(length: 5, nullable: true)]
    private ?string $reference = null;

    #[ORM\Column]
    private ?bool $is_visible = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\ManyToOne(inversedBy: 'computers')]
    private ?User $author = null;

    #[ORM\ManyToOne(inversedBy: 'computers')]
    private ?Brand $brand = null;

    #[ORM\OneToMany(mappedBy: 'computers', targetEntity: Favorite::class)]
    private Collection $favorites;

    public function __construct()
    {
        $this->favorites = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): self
    {
        $this->model = $model;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getReleaseYear(): ?int
    {
        return $this->release_year;
    }

    public function setReleaseYear(int $release_year): self
    {
        $this->release_year = $release_year;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(?string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function isIsVisible(): ?bool
    {
        return $this->is_visible;
    }

    public function setIsVisible(bool $is_visible): self
    {
        $this->is_visible = $is_visible;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getBrand(): ?Brand
    {
        return $this->brand;
    }

    public function setBrand(?Brand $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    /**
     * @return Collection<int, Favorite>
     */
    public function getFavorites(): Collection
    {
        return $this->favorites;
    }

    public function addFavorite(Favorite $favorite): self
    {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites->add($favorite);
            $favorite->setComputers($this);
        }

        return $this;
    }

    public function removeFavorite(Favorite $favorite): self
    {
        if ($this->favorites->removeElement($favorite)) {
            // set the owning side to null (unless already changed)
            if ($favorite->getComputers() === $this) {
                $favorite->setComputers(null);
            }
        }

        return $this;
    }

    /**
     * @param User $user
     * @return boolean
     */
    public function isUserfav (User $user): bool
    {
        foreach($this->favorites as $favorites){
            if($favorites ->getUsers() === $user) return true;
        }
        return false;
    }
}

src/Form/ComputerType.php
<?php

namespace App\Form;

use App\Entity\Computer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ComputerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('model')
            ->add('description')
            ->add('price')
            ->add('release_year')
            ->add('image')
            ->add('brand')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Computer::class,
        ]);
    }
}

src/Controller/ComputerController.php
<?php

namespace App\Controller;

use App\Entity\Computer;
use App\Entity\Favorite;
use App\Form\ComputerType;
use App\Repository\ComputerRepository;
use App\Repository\FavoriteRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/computer')]
class ComputerController extends AbstractController
{
    #[Route('/', name: 'app_computer_index', methods: ['GET'])]
    #[IsGranted('ROLE_ADMIN')]
    public function index(ComputerRepository $computerRepository): Response
    {
        return $this->render('computer/index.html.twig', [
            'computers' => $computerRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_computer_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_USER')]
    public function new(Request $request, ComputerRepository $computerRepository): Response
    {
        $author = $this->getUser();
        $computer = new Computer();
        $form = $this->createForm(ComputerType::class, $computer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $lettres = range('A', 'Z');
            shuffle($lettres);
            $lettre = array_shift($lettres);
            shuffle($lettres);
            $lettre .= array_shift($lettres);
            shuffle($lettres);
            $lettre .= array_shift($lettres);
            // un nombre sur 4 digit au hasard
            $nombre = mt_rand(10, 99);
            $reference = $lettre.$nombre;

            $computer->setReference($reference);
            $computer->setAuthor($author);
            $computer->setIsVisible(true);
            $computerRepository->save($computer, true);
            return $this->redirectToRoute('app_computer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('computer/new.html.twig', [
            'computer' => $computer,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_computer_show', methods: ['GET'])]
    public function show(Computer $computer): Response
    {
        return $this->render('computer/show.html.twig', [
            'computer' => $computer,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_computer_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_USER')]
    public function edit($id, Request $request, Computer $computer, ComputerRepository $computerRepository): Response
    {
        $thisAnnonce = $computerRepository->find($id);
        if($thisAnnonce->isIsVisible() == false) {
            $this->addFlash('Erreur', 'Cette annonce n\'existe plus');
            return $this->redirectToRoute('app_home');
        }
        $form = $this->createForm(ComputerType::class, $computer);
        $form->handleRequest($request);
        $author = $this->getUser();
        if($author == false){
            $this->addFlash('Erreur', 'Vous devez avoir un compte pour ajouter/modifier une anonnce');
            return $this->redirectToRoute('app_home');
        }

        if($this->container->get('security.authorization_checker')->isGranted('ROLE_ADMIN') or $computer->getAuthor()==$author) {
            if ($form->isSubmitted() && $form->isValid()) {
                $computerRepository->save($computer, true);

                $this->addFlash('Succès', 'Votre annonce a bien été modifiée');
                return $this->redirectToRoute('app_computer_index', [], Response::HTTP_SEE_OTHER);
            }
        }else {
            $this->addFlash('Erreur', 'Vous n\'êtes pas l\'auteur de cette anonnce');
            return $this->redirectToRoute('app_home');
        }

        return $this->renderForm('computer/edit.html.twig', [
            'computer' => $computer,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_computer_delete', methods: ['POST'])]
    #[IsGranted('ROLE_USER')]
    public function delete(Computer $computer, ComputerRepository $computerRepository): Response
    {
        $author = $this->getUser();
        if($author == false){
            $this->addFlash('Erreur', 'Votre devez avoir un compte pour ajouter une annonce');
            return $this->redirectToRoute('home');
        }
        if($this->container->get('security.authorization_checker')->isGranted('ROLE_ADMIN') or $computer->getAuthor() == $author) {
            $computer->setisVisible(false);
            $computerRepository->save($computer);
        }else {
            $this->addFlash('Erreur', "Vous n'êtes pas l'auteur de cette annonce !" );
            return $this->redirectToRoute('app_annonce_show', ['id' => $computer->getId()]);
        }
        $this->addFlash('Succès', "Votre annonce a bien été supprimée !" );

        return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}/fav', name: 'app_annonce_fav', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_USER')]
    public function favUserAnnonce(Computer $computer, FavoriteRepository $favRepo): Response
    {
        $user = $this->getUser();
        if(!$user) return $this->redirectToRoute('app_login');

        if($computer->isUserfav($user)){
            $signedUp = $favRepo->findOneBy([
                'computers' => $computer,
                'users' => $user
            ]);
            $favRepo ->remove($signedUp);
            $this->addFlash('Erreur', "Cette annonce n'est plus dans vos favoris" );

            return $this->redirectToRoute('app_home');
        }

        $newFav = new Favorite();
        $newFav->setComputers($computer)
            ->setUsers($user);

        $favRepo->save($newFav);
        $this->addFlash('Succès', "Cette annonce est désormais dans vos favoris" );

        return $this->redirectToRoute('app_profile');
    }
}

templates/computer/_delete_form.html.twig
<form method="post" action="{{ path('app_computer_delete', {'id': computer.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette annonce ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ computer.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/computer/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/computer/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Computer{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h1 class="text-center mt-5">Édition {{ computer.model}} </h1>
        {{ include('computer/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
        <div class="text-center">
            {{ include('computer/_delete_form.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/computer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Computer index{% endblock %}

{% block body %}

    <div class="container mt-5">
        <h1 class="text-center">Liste des Annonces d'ordinateurs</h1>

        <table class="table mt-5">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Model</th>
                    <th>Description</th>
                    <th>Price</th>
                    <th>Release_year</th>
                    <th>Reference</th>
                    <th>Is_visible</th>
                    <th>Image</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
            {% for computer in computers %}
                <tr>
                    <td>{{ computer.id }}</td>
                    <td>{{ computer.model }}</td>
                    <td>{{ computer.description }}</td>
                    <td>{{ computer.price }}</td>
                    <td>{{ computer.releaseYear }}</td>
                    <td>{{ computer.reference }}</td>
                    <td>{{ computer.isVisible ? 'Yes' : 'No' }}</td>
                    <td>{{ computer.image }}</td>
                    <td>
                        <a class="btn btn-primary" href="{{ path('app_computer_show', {'id': computer.id}) }}">show</a>
                        <a class="btn btn-warning" href="{{ path('app_computer_edit', {'id': computer.id}) }}">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="9">Aucune Annonce n'a été créée</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="text-center">
            <a class="btn btn-success" href="{{ path('app_computer_new') }}">Créer une nouvelle annonce</a>
        </div>
    </div>
{% endblock %}

templates/computer/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Computer{% endblock %}

{% block body %}

    <div class="container mt-5">
        <h1 class="text-center">Créer une nouvelle annonce d'ordinateur</h1>

        {{ include('computer/_form.html.twig') }}

        <div class="text-center mb-5">
            <a class="btn btn-secondary" href="{{ path('app_home') }}">Annuler</a>
        </div>
    </div>
{% endblock %}

templates/computer/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Computer{% endblock %}

{% block body %}
<div class="container mt-5">
    <h1 class="text-center mt-4">{{ computer.model }}</h1>

    <div class="d-flex justify-content-center">
        <img class="card-show" src="{{ computer.image }}" alt="Card image cap">
    </div>
    <div class="jumbotron mt-5">
        <h2 class="display-4">{{computer.model}}</h2>
        <p class="lead">{{ computer.description }}</p>
        <hr class="my-4">
        <p>Prix : {{ computer.price }}€</p>
        <p>Année de sortie : {{ computer.releaseYear }}</p>
        <p>Numéro de série : {{ computer.reference }}</p>
        <p>Marque : <a class="text-primary h4" href="{{path('app_tab', {'id': computer.brand.id})}}" class="card-text">{{computer.brand.name}}</a></p>
    </div>

    {% if app.user %}
        <div class="d-flex justify-content-around">
            <a class="btn btn-warning" href="{{ path('app_computer_edit', {'id': computer.id}) }}">Éditer</a>
            {{ include('computer/_delete_form.html.twig') }}
        </div>
    {% endif %}
</div>
{% endblock %}